stages:
  - build
make-image:
  image: docker:latest
  variables:
    CONTAINER_NAME: $CI_REGISTRY/0xbad0c0d3/cronie/
  when: always
  stage: build
  before_script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  after_script:
    - docker container rm $(docker container ls -qaf label=$CI_JOB_NAME)
    - docker rmi -f $(docker image ls -qf label=$CI_JOB_NAME)
  script:
    - docker build --label=$CI_JOB_NAME -t $CONTAINER_NAME ./docker
    - docker push $CONTAINER_NAME